name: Github Action No. 2

on:
  push:
    branches: ["main"]

# permission:
#   contents: read
#   pages: write
#   id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: action/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependancies
        run: npm ci
      - name: Build Project
        run: npm run build
        # uses: ac
# deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url}}